### ISSUE TITLE
~LogMessage should be declared noexcept(false)

### ISSUE THREAD

**Issue by eigenbom** [andrew-d/cpplog#25]
C++11 implicitly makes destructors noexcept, causing the system to terminate() instead of throwing.

`~LogMessage noexcept(false)`

**Comment by andrew-d** [comment]
Thanks for the report!

**Comment by eigenbom** [comment]
hey no worries, thx for the library!

was also wondering if ~LogMessage() needs to be virtual? (or is it for extendability?)

**Comment by andrew-d** [comment]
Yeah, it's for extendability - cpplog supports defining a custom `LOG_LEVEL` macro (see [here][1] where we only define ours if it's not previously defined).  If someone created one that used a subclass of `LogMessage` (maybe along with a custom logger that does extra stuff with the message), we need the destructor on the base class to be virtual.

[1]: https://github.com/andrew-d/cpplog/blob/master/cpplog.hpp#L1091

**Comment by eigenbom** [comment]
AH yeah cool, no problem :)
